### PR TITLE
Fix #133: Fix issues found by coverity scan

### LINKED ISSUE #133: Fix issues found by coverity scan
- `io.getlime.security.powerauth.lib.cmd.steps.model.CreateActivationStepModel.getApplicationSecret() -> CID 350585 (#1 of 1): Use of hard-coded cryptographic key (HARDCODED_CREDENTIALS)

- `io.getlime.security.powerauth.lib.cmd.steps.model.PrepareActivationStepModel.getApplicationSecret()` -> CID 350586 (#1 of 1): Use of hard-coded cryptographic key (HARDCODED_CREDENTIALS)

### PR DESCRIPTION
**Pull request by romanstrobl**
I removed the hardcoded values.

### CODE REVIEW

File: powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/ConfigurationUtil.java [hunk 1]
```diff
@@ -46,7 +42,7 @@ public static String getApplicationKey(JSONObject clientConfigObject) {
         if (clientConfigObject.get("applicationKey") != null) {
             return (String) clientConfigObject.get("applicationKey");
         } else {
-            return expectedApplicationKey;
+            return null;
```
Comment (petrdvorak) [inline powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/ConfigurationUtil.java]: This code can be simplified - the `if-else` is now probably redundant... ? This is in all situations...

Comment (romanstrobl) [reply powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/ConfigurationUtil.java]: Fixed.
