### PR TITLE
Fix #49: Null pointer exception when HTTP method is missing for validate token

### LINKED ISSUE #49: Null pointer exception when HTTP method is missing for validate token
See error:

```json
{
      "name" : "Unknown error occurred",
      "description" : null,
      "status" : "ERROR",
      "object" : {
        "cause" : null,
        "stackTrace" : [
          {
            "methodName" : "execute",
            "fileName" : "VerifyTokenStep.java",
            "lineNumber" : 80,
            "className" : "io.getlime.security.powerauth.lib.cmd.steps.VerifyTokenStep",
            "nativeMethod" : false
          },
          {
            "methodName" : "main",
            "fileName" : "Application.java",
            "lineNumber" : 230,
            "className" : "io.getlime.security.powerauth.app.cmd.Application",
            "nativeMethod" : false
          }
        ],
        "message" : null,
        "localizedMessage" : null,
        "suppressed" : [ ]
      }
```

### PR DESCRIPTION
**Pull request by romanstrobl**
This PR fixes:
- Fix #49: Null pointer exception when HTTP method is missing for validate token
- Avoid casts in `CounterUtil`, in memory type of result status object may differ from type stored in file

### CODE REVIEW

File: powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/CounterUtil.java [hunk 1]
```diff
@@ -40,8 +41,8 @@
      */
     public static byte[] getCtrData(BaseStepModel model, StepLogger stepLogger) {
         byte[] ctrData = new byte[16];
-        long counter = (long) model.getResultStatusObject().get("counter");
-        int version = (int) model.getResultStatusObject().get("version");
+        long counter = new BigDecimal(model.getResultStatusObject().get("counter").toString()).longValue();
```
Comment (petrdvorak) [inline powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/CounterUtil.java]: This seems a bit overengineered: `TooManyConversionException`. :)

I would probably favor something like:

```java
long counter = safeLong(model.getResultStatusObject().get("counter"));

/// ...

private long safeLong(Object o) {
    return o instanceof Long ? (long) o : 0;
}

```

Comment (romanstrobl) [reply powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/CounterUtil.java]: Ok, why not.

Comment (romanstrobl) [reply powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/CounterUtil.java]: I introduced safe handling of `long`, `int` and `String` values to avoid dangerous casts in the code. The ObjectMapper is configured to return `Long` type for deserialized numbers instead of `Integer` so that the same type is used in memory and during deserialization. Previously the type was either `Long` (in memory counter) or `Integer` (counter read from file) which lead to class cast exceptions.
