### PR TITLE
Fix #475: Add support for protocol version 3.3

### LINKED ISSUE #475: Add support for protocol version 3.3
Add support for version `3.3`, currently only `3.2` is supported.

```
java.lang.IllegalStateException: Unsupported PowerAuth version: 3.3
```

### PR DESCRIPTION
**Pull request by romanstrobl**

### CODE REVIEW

File: powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/EncryptStep.java [hunk 1]
```diff
@@ -115,37 +121,50 @@ public StepContext<EncryptStepModel, EciesEncryptedResponse> prepareStepContext(
...
+        final PublicKey encryptionPublicKey = temporaryPublicKey == null ?
+                model.getMasterPublicKey() :
+                KEY_CONVERTOR.convertBytesToPublicKey(java.util.Base64.getDecoder().decode(temporaryPublicKey));
 
         // Prepare the encryption header
         final EncryptorId encryptorId;
-        final PowerAuthEncryptionHttpHeader header;
-        switch (model.getScope()) {
-            case "application" -> {
+        ClientEncryptor encryptor = null;
```
Comment (banterCZ) [inline powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/EncryptStep.java:145]: Just to be safe, making the variables `final` could be fine if the refactor is not too complicated.

File: powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/TemporaryKeyUtil.java [hunk 2]
```diff
@@ -0,0 +1,199 @@
...
+import java.time.Instant;
+import java.time.temporal.ChronoUnit;
+import java.util.*;
+
+/**
+ * Helper class for fetching temporary keys.
+ *
+ * @author Roman Strobl, roman.strobl@wultra.com
+ */
+public class TemporaryKeyUtil {
```
Comment (banterCZ) [inline powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/util/TemporaryKeyUtil.java:60]: A utility class may hide the constructor.

**Review by banterCZ — APPROVED** [review]
