### PR TITLE
Fix #525: Coverity - Possible NPE

### LINKED ISSUE #525: Coverity - Possible NPE
### Affected product(s) and version(s)

_No response_

### Environment

_No response_

### Steps to reproduce, current result, expected result

_No response_

### Log output

_No response_

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: powerauth-java-cmd-lib/src/main/java/com/wultra/security/powerauth/lib/cmd/util/TemporaryKeyUtil.java [hunk 1]
```diff
@@ -124,6 +124,13 @@ private static byte[] getSecretKey(StepContext<? extends BaseStepData, ?> stepCo
         } else if (scope == EncryptorScope.ACTIVATION_SCOPE) {
             final byte[] appSecretBytes = Base64.getDecoder().decode(appSecret);
             final SecretKey transportMasterKey = model.getResultStatus().getTransportMasterKeyObject();
+            if (transportMasterKey == null) {
+                stepContext.getStepLogger().writeError(
+                        stepContext.getStep().id() + "-failed",
+                        "Get Secret Key Failed",
```
Comment (romanstrobl) [inline powerauth-java-cmd-lib/src/main/java/com/wultra/security/powerauth/lib/cmd/util/TemporaryKeyUtil.java:130]: Let's change the message to `Get Transport Master Key Failed`, there are many secret keys.

**Review by romanstrobl — APPROVED** [review]
I suggest to change the message, otherwise looks OK.
