### PR TITLE
Fix #372: Edit data parsing in offline signature calculation

### LINKED ISSUE #372: Edit data parsing in offline signature calculation
Method `calculateOfflineSignature` in `cmd-lib` does not support adding a [new attribute](https://github.com/wultra/powerauth-webflow/blob/develop/docs/Off-line-Signatures-QR-Code.md#forward-compatibility). When a proximityCheck OTP attribute is added before `nonce`, a wrong signature is produced.

Edit the data parser to respect following scenarios:

| data[i]      | 0  | ... | 5    | 6     | 7        | 8        |
|-------------|----|-----|------|-------|----------|----------|
| with OTP    | id | ... | flag | otp   | nonce    | sign -\| |
| without OTP | id | ... | flag | nonce | sign -\| |          |

### PR DESCRIPTION
**Pull request by jnpsk**
Fix #372 
When offline data string has 8 components, otp is expected before nonce.

### CODE REVIEW

File: powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/ComputeOfflineSignatureStep.java [hunk 1]
```diff
@@ -167,8 +170,9 @@ private String calculateOfflineSignature(final String offlineData, final StepLog
         }
         final String operationId = parts[0];
         final String operationData = parts[3];
-        final String nonce = parts[5];
+        final String nonce = parts[parts.length - 2];
         final String signatureLine = parts[parts.length - 1];
+        final String otp = parts.length == 8 ? parts[parts.length - 3] : null;
```
Comment (banterCZ) [inline powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/ComputeOfflineSignatureStep.java:175]: 🤔 Is there any way to make it more robust in the future, if we add another attribute after OTP?

**Review by banterCZ — APPROVED** [review]
Looks working. Adding @romanstrobl to the loop. Probably we are not adding attributes so often, are we?

File: powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/ComputeOfflineSignatureStep.java (hunk 1 above)
Comment (jnpsk) [reply powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/ComputeOfflineSignatureStep.java]: I was thinking about joining all the unexpected attributes together (indices 5 to len-3). However if there is a new attribute in offline qr code it does not have to be part of the signature base necessarily (such as a new informative string for a user).

But you are right about robustness. I came with a new parsing rule in the new commit. However, there is still a hypothetical scenario when the solution is not robust enough. (Adding a new numerical attribute and allowing not to use proximity check). The length of the totp can change according to a server configuration.
+ We should probably add to the [documentation](https://github.com/wultra/powerauth-webflow/blob/develop/docs/Off-line-Signatures-QR-Code.md#forward-compatibility) that numerical value before nonce is treated as totp?

**Review by romanstrobl — APPROVED** [review]
I think it is OK, we cannot predict future changes.
