### PR TITLE
Fix #67: Crypto 3.0: Improve testability of powerauth-java-cmd-lib

### LINKED ISSUE #67: Crypto 3.0: Improve testability of powerauth-java-cmd-lib
In order to use `powerauth-java-cmd-lib` for end-to-end tests we should implement following improvements:

* Use `StepLogger` interface instead of `JsonStepLogger` class in all steps to allow multiple implementations of `StepLogger`. `JsonStepLogger` is currently used as parameter of each step, however interface should be prefered over implementation.
* Implement an in-memory Object-based `StepLogger` with methods useful for assertions in tests.
* Switch to long values in numeric counter to avoid `ClassCastException` in `ResultStatusObject`.

### PR DESCRIPTION
**Pull request by romanstrobl**
- Fix #67: Crypto 3.0: Improve testability of powerauth-java-cmd-lib
   - Use `StepLogger` interface instead of `JsonStepLogger` class in all steps to allow multiple implementations of `StepLogger`. `JsonStepLogger` is currently used as parameter of each step, however interface should be prefered over implementation.
   - Implement an in-memory Object-based `StepLogger` with methods useful for assertions in tests.
   - Switch to long values in numeric counter to avoid `ClassCastException` in `ResultStatusObject`.
- Use `Response` instead of `Map<String, Object>` in `VerifyTokenStep` and `VerifySignatureStep`
- Execute `serverCallOK` only once per step
- Fixed NPE in counter
- Log `serverCallConnectionError` as an error
- Fixed typos
- Versioning of activation status and activation remove to allow testing different endpoint versions

### CODE REVIEW

File: powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/PrepareActivationStep.java [hunk 1]
```diff
@@ -198,17 +198,18 @@ public JSONObject execute(JsonStepLogger stepLogger, Map<String, Object> context
...
+                    stepLogger.writeServerCallOK(encryptedResponseL1, HttpUtil.flattenHttpHeaders(response.getHeaders()));
+                }
+
+                // Read activation layer 1 response and decrypt it
                 byte[] macL1 = BaseEncoding.base64().decode(encryptedResponseL1.getMac());
                 byte[] encryptedDataL1 = BaseEncoding.base64().decode(encryptedResponseL1.getEncryptedData());
                 EciesCryptogram responseCryptogramL1 = new EciesCryptogram(macL1, encryptedDataL1);
                 byte[] decryptedDataL1 = eciesEncryptorL1.decryptResponse(responseCryptogramL1);
 
-                if (stepLogger != null) {
```
Comment (petrdvorak) [inline powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/PrepareActivationStep.java]: Why are we removing this logging point? We would like to log decrypted data as well, right? Maybe using `writeServerCallOK` is not the best way of logging, but we should log the original request / response...

File: powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/PrepareActivationStep.java [hunk 2]
```diff
@@ -218,10 +219,6 @@ public JSONObject execute(JsonStepLogger stepLogger, Map<String, Object> context
                 EciesCryptogram responseCryptogramL2 = new EciesCryptogram(macL2, encryptedDataL2);
                 byte[] decryptedDataL2 = eciesEncryptorL2.decryptResponse(responseCryptogramL2);
 
-                if (stepLogger != null) {
```
Comment (petrdvorak) [inline powerauth-java-cmd-lib/src/main/java/io/getlime/security/powerauth/lib/cmd/steps/v3/PrepareActivationStep.java]: dtto

**Comment by romanstrobl** [comment]
I added the logging of decrypted L1 and L2 responses in activation as well as decrypted response in vault unlock.
